version: "3.8"
services:
  web:
    restart: always
    image: web:1
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db
#    volumes:
#      - akbar
    command: ["./wait-for-it.sh", "db:9042", "-s" ,"--", "php", "test.php", "||", "apache2-foreground"]
  db:
    image: cassandra
    ports:
      - "9042:9042"

#volumes:
#  akbar:
#    external:
